Page structure updates for Course Management
joschahenningsen/TUM-Live pull request #1008
Opened 2023-04-25 11:50 UTC by mono424

### Motivation and Context
Lecture Items are not very easy to edit, as the edit functionality is hidden in a small error next to destructive actions.
Course overview page is not very user-friendly as it has much information on one single page.

### Description
Added tabs to the 3 main functionalities of the course management page. Added a more visible button to
the lectures to make them easier to edit.

### Steps for Testing
Prerequisites:
- 1 Lecturer

1. Log in
2. Navigate to a Management Page of a Course
3. Click through tabs and see if the content is displayed accordingly
4. Try to change a Lecture by clicking the new button.

### Screenshots
<img width="481" alt="Bildschirmfoto 2023-04-25 um 13 50 02" src="https://user-images.githubusercontent.com/17506411/234267665-2b18c2e6-f6f3-450b-abd0-0f30d87eb5db.png">

<img width="924" alt="Bildschirmfoto 2023-04-25 um 13 50 31" src="https://user-images.githubusercontent.com/17506411/234267767-7156b8e8-5548-49ab-9a21-4bb208be252c.png">

2023-04-25 14:07 UTC, joschahenningsen commented
Love the idea! Can you quickly resolve the conflicts? @mono424

2023-04-25 14:14 UTC, mono424 commented
> Love the idea! Can you quickly resolve the conflicts? @mono424 

Thanks! 🙌
Is resolved by today, I was interrupted by a lecture 😬

2023-04-25 15:30 UTC, joschahenningsen commented
Thanks! Looks great, let's discuss the specifics tomorrow in the meeting :)

2023-04-26 15:18 UTC, joschahenningsen requested changes
As discussed in the meeting, can you switch the settings and external participants tab? Then it's ready to merge imo.

2023-04-27 08:19 UTC, joschahenningsen approved these changes
Amazing!

2023-04-27 08:19 UTC, merged