Feature/edit vod
joschahenningsen/TUM-Live pull request #1049
Opened 2023-05-29 15:03 UTC by mono424

### Motivation and Context
Currently a user who wants to update the VoD-Media, needs to delete the VoD and recreate it with updated Video files.

### Description
Allow a user to update VOD Media files.

### Steps for Testing

Prerequisites:
- 1 Lecturer
- 1 VoD

1. Log in
2. Navigate to a Course Admin Page
3. Click on edit on a VoD
4. Select new Video Files and Save VoD

### Screenshots
![Bildschirmfoto 2023-05-29 um 17 03 08](https://github.com/joschahenningsen/TUM-Live/assets/17506411/7d3d7b42-0e9f-4c28-8f94-16cedba316bd)

2023-06-04 13:26 UTC, mono424 commented
Just as a note :)
Still some issues to fix:
- ERRO[04.06.2023 15:24:56] Error transcoding audio                       error="transcode stream audio: exit status 1: File '/Users/khadim/mass/2022/W/EAGAbschied/25311.m4a' already exists. Overwrite? [y/N] "

- Are the thumbnails being recreated ?

2023-06-13 08:16 UTC, MatthiasReumann requested changes
Works and looks great 🌟

A few nitpicks, but other than that I think this one is good to go.

2023-06-13 08:16 UTC, MatthiasReumann commented on web/ts/edit-course.ts
> +        console.log(this.newCombinedVideo);
```suggestion
```

2023-06-13 08:16 UTC, MatthiasReumann commented on api/stream.go
> +		c.AbortWithStatus(http.StatusBadRequest)
^ same here

2023-06-13 08:16 UTC, MatthiasReumann commented on api/stream.go
> +			c.AbortWithStatus(http.StatusNotFound)
```suggestion
			_ = c.Error(tools.RequestError{
	                          Status:        http.StatusNotFound,
	                          CustomMessage: "Large Thumbnail not found",
                        })
                        return
```

2023-06-14 04:37 UTC, MatthiasReumann approved these changes
Thanks! 🚀

2023-06-14 05:17 UTC, joschahenningsen approved these changes
Nice!

2023-06-14 05:17 UTC, merged