`bug` Delete Chat Replies on Delete
joschahenningsen/TUM-Live pull request #1064
Opened 2023-06-13 12:13 UTC by MatthiasReumann

### Motivation and Context
Currently if a message with replies is deleted only the "base" message is deleted, i.e. replies are kept in the database. In other words `deleted_at` is only not-null for base messages. As a consequence, each time we fetch messages deleted "ghost" replies are transmitted also. 

This PR fixes this issue.

### Description
Add `DeleteReplies` to `ChatDao` and call in delete handler.

### Steps for Testing
- 1 Account
- 1 Livestream with the chat activated

1. Log in
2. Navigate to a Livestream
3. Write a message and reply to that message 
4. Delete the base message
5. Use DataGrip (or similar) to check that both the base message and the replies are deleted

2023-06-13 22:03 UTC, mono424 approved these changes
Checked locally with DataGrip, looks great! 🚀

2023-06-13 22:04 UTC, joschahenningsen reviewed
Looks good! Do we ever need to delete a chat without deleting it's replies? If not we can also merge these methods into one.

2023-06-14 04:23 UTC, MatthiasReumann commented
> Looks good! Do we ever need to delete a chat without deleting it's replies? If not we can also merge these methods into one.

Probably not. Good idea! 👍🏻

2023-06-14 04:39 UTC, MatthiasReumann commented
Please ignore the `go test / test` error. We need to update the workflow to `go1.20` 😬

2023-06-14 05:15 UTC, joschahenningsen requested changes

2023-06-14 05:15 UTC, joschahenningsen commented on dao/chat.go
> +		DB.Delete(&model.Chat{}, "reply_to = ?", id).Error)
This seems a little cleaner

```suggestion
	return DB.Where("id = ? OR reply_to = ?").Delete(&model.Chat{}).Error
```

2023-06-21 09:39 UTC, joschahenningsen approved these changes

2023-06-21 09:39 UTC, merged