Hide current semester if show all is pressed and highlight current se…
joschahenningsen/TUM-Live pull request #1205
Opened 2023-10-23 10:08 UTC by SebiWrn

### Motivation and Context
Fixes #1184 

### Description
Currently selected semester will be highlighted in semester list but won't be shown twice at the top

### Steps for Testing
On the main page just click show all on the semesters list

### Screenshots
![semester_selection_0](https://github.com/TUM-Dev/gocast/assets/67778694/0b51aa51-a2c8-4161-a36c-ef0d41579a49)
![semester_selection_1](https://github.com/TUM-Dev/gocast/assets/67778694/e33e9c52-644c-4ef3-8c32-ed21659e8850)

2023-11-08 00:04 UTC, alexanderstephan requested changes
Works perfectly. 👍 I would only suggest some minor style changes in this case.

2023-11-08 00:04 UTC, alexanderstephan commented on web/template/home.gohtml
> +                            :class="{'border-l-4 bg-blue-100/50 border-blue-500/50 dark:bg-indigo-500/25 dark:border-indigo-600/50': i == selectedSemesterIndex, }"
```suggestion
                            :class="{'border-l-4 bg-blue-100/50 border-blue-500/50 dark:bg-indigo-500/25 dark:border-indigo-600/50': i == selectedSemesterIndex }"
```
Is that trailing comma intended?

2023-11-08 00:04 UTC, alexanderstephan commented on web/template/home.gohtml
> +                  x-text="semesters[selectedSemesterIndex]?.FriendlyString()" x-show="!navigation.getChild('allSemesters').value"></span>
```suggestion
                  x-text="semesters[selectedSemesterIndex]?.FriendlyString()"
                  x-show="!navigation.getChild('allSemesters').value"></span>
```

2023-11-19 16:22 UTC, SebiWrn commented on web/template/home.gohtml
> +                            :class="{'border-l-4 bg-blue-100/50 border-blue-500/50 dark:bg-indigo-500/25 dark:border-indigo-600/50': i == selectedSemesterIndex, }"
No that wasn't intended, thanks

2023-11-20 16:54 UTC, alexanderstephan approved these changes
Thanks for the update, looks great now! 👍

2023-11-20 16:55 UTC, merged