1177 course import deduplicate emails
joschahenningsen/TUM-Live pull request #1236
Opened 2023-11-17 10:31 UTC by barisgul15

### Motivation and Context
Issue 1177: https://github.com/orgs/TUM-Dev/projects/10/views/1?pane=issue&itemId=41336294
The array coming from TUMonline has some duplicates in contacts and these need to be eliminated.

### Description

The data coming from TUMonline sometimes duplicates contacts of some courses. course.contacts has 5 attributes:
first_name, last_name, email, main_contact, role.
All cases considered, the most distinctive among them is e-mail. So a script is added to modify the array before it is used for course contacts while importing courses.

### Steps for Testing

Prerequisites:
- Having admin rights

1. Log in
2. Click admin in the menu
3. Click import courses
4. Find a course that used to have duplicate contacts: e.g.  Einführung in die Games Eng(IN0031), IN2064, ...
5. Confirm that there are not duplicate contacts anymore.

### Screenshots

Before there was two Vortragende*r, Leiter*in, but the course has only one actually:
![twoTimesListedGames](https://github.com/TUM-Dev/gocast/assets/70471039/1f3451fe-f15d-49eb-8ca8-7a1348962ed1)
After the changes, the duplicate is eliminated:
![Games_duplicates_eliminated](https://github.com/TUM-Dev/gocast/assets/70471039/cd872cf5-4e0a-49ee-8168-556c6289d37e)

2023-11-19 16:29 UTC, SebiWrn requested changes
Please move the script tag to the correct typescript files and use it from there

2023-11-20 15:39 UTC, barisgul15 commented
The location of the used filtering function is changed from course-import.gohtml to course-import.ts.

2023-12-13 15:08 UTC, SebiWrn requested changes
I think there is still an issue with the checkboxes, because you just change the value in the contacts from your method, but the send mail method still uses the whole contact list without the updated values.
With that I think the checkboxes won't work and everybody will get an email even if you don't select them.

2024-09-23 14:55 UTC, SebiWrn commented
If you still want to merge this PR please address the issues and reopen the PR

2024-09-23 14:55 UTC, closed without merging