Skip initial silence
joschahenningsen/TUM-Live pull request #1262
Opened 2023-12-10 15:00 UTC by Mjaethers

### Motivation and Context

Closes #1188 
Instead of opening a VOD, waiting for it to load, clicking skip, and waiting for it to load again there should be a user setting which allows the player to immediately skip past the first period of silence.

### Description

A new user setting to allows automatic skipping was added, this can be modified in the users settings page.
When this setting is enabled, the watch page sets the progress of the stream VOD to the maximum of the watch progress in the database and the end of the first period of silence.

### Steps for Testing

**Unfortunately I am not sure yet. I would somehow need to add an example VOD from the real database to my database or use a runner/worker to have an example VOD with recognized silence.**

### Screenshots

![Screenshot_Skip_Silence_Setting](https://github.com/TUM-Dev/gocast/assets/61728152/a60a9e00-2c4c-4e31-8a66-89e106173bd9)

2024-01-18 18:09 UTC, meandaD approved these changes
Works smoothly!

2024-01-18 18:11 UTC, meandaD commented
Before merging it to dev, I would like to make sure: we do rebuild the database container using "/docs/static/tum-live-starter.sql" for each deployment, right?

2024-01-18 19:01 UTC, Mjaethers commented
I'm afraid I don't quite follow.
My understanding of the file is that it is used to create a local docker container, as outlined in the [docs](https://github.com/TUM-Dev/gocast#setup-database) and that it has no impact on the database used in deployment. As far as I know this is just for testing during development.
The container would only be rebuilt if one were to manually rebuild it then.

But we can always get someone who is more familiar with the system in here if need be.

2024-01-18 19:03 UTC, Mjaethers commented
I thought it would make sense to commit these changes as well for future testing in this area, but we can also exclude this file if it's cluttering the db.

2024-01-18 20:09 UTC, meandaD commented
Yes, I think changes to sql files should be pushed anyway, but they need to be handled more carefully when deployed. I'd like to hear from someone more familiar with the project on this issue.

2024-01-19 09:51 UTC, Mjaethers commented
@alexanderstephan or @joschahenningsen what are your thoughts on the matter?

2024-01-19 10:10 UTC, joschahenningsen requested changes
`tum-live-starter.sql` Is just for local testing and can be modified without worries :)

2024-01-19 10:10 UTC, joschahenningsen commented on web/watch.go
> +	log "github.com/sirupsen/logrus"
```suggestion
```

2024-01-19 10:10 UTC, joschahenningsen commented on web/watch.go
> +			log.Printf("Couldn't decode user setting: %v\n", err)
```suggestion
			logger.Error("Couldn't decode user setting", "err", err)
```

2024-01-19 10:54 UTC, joschahenningsen approved these changes
🍻

2024-01-19 11:55 UTC, merged