Added Filter by Role to user search
joschahenningsen/TUM-Live pull request #1278
Opened 2023-12-21 18:51 UTC by SebiWrn

### Motivation and Context
You can now filter users by their role, improves administration and overview over admins.

### Steps for Testing
Prerequisites:
- 1 Admin

1. Log in
2. Navigate to User management page
3. View the new Dropdown

### Screenshots
![image](https://github.com/TUM-Dev/gocast/assets/67778694/cbe1da59-8967-4d02-9f06-38ffd06a8661)

2024-01-10 23:33 UTC, meandaD commented
There's a small problem: after filtering, the user's email doesn't seem to be displayed

2024-11-21 09:54 UTC, karjo24 commented
Filtering locally results in no show of potential results. Simplest case of this is filtering for students without query string. Change the API instead.

2024-11-21 10:17 UTC, karjo24 commented
> There's a small problem: after filtering, the user's email doesn't seem to be displayed

I cannot reproduce this problem in Mozilla Firefox for Ubuntu 132.0.2 (64-Bit) or Google Chrome Version 130.0.6723.58 (Official Build) (64-bit).

2024-11-22 14:55 UTC, joschahenningsen requested changes, later dismissed
Looks great, just added two remarks

2024-11-22 14:55 UTC, joschahenningsen commented on api/users.go
> +	// Removed in order to make the search work with empty query but selected role
```suggestion
	// make the search work with empty query but selected role
```

2024-11-22 14:55 UTC, joschahenningsen commented on api/users.go
> +	role, err := strconv.ParseUint(rQ, 10, 64)
catch the error separately and return bad request if parsing failed.

2024-11-25 10:34 UTC, joschahenningsen commented on api/users.go
> +		tools.RenderErrorPage(c, http.StatusBadRequest, "invalid role")
API endpoints should not render HTML pages on error but rather use 
https://github.com/TUM-Dev/gocast/blob/95804eb169b5a717f715c55fe6858478c098ccec/web/course.go#L31

2025-01-10 16:37 UTC, kordianbruck approved these changes

2025-01-10 16:37 UTC, kordianbruck commented on api/users.go
>  	q = reg.ReplaceAllString(q, "")
all of these variable names are hard to understand without context. Also why are we only enforcing the regex on one of the two paramters? Does rQ not need to be checked for validity?

2025-01-10 16:38 UTC, kordianbruck commented on api/users.go
>  	q = reg.ReplaceAllString(q, "")
Edited the PR, PTAL if you think thats better (otherwise revert my commit please).

2025-01-10 17:00 UTC, karjo24 commented on api/users.go
>  	q = reg.ReplaceAllString(q, "")
> Also why are we only enforcing the regex on one of the two paramters? Does rQ not need to be checked for validity?

Probably hard to immediately understand and therefore bad code, but it's checked before it's used: https://github.com/TUM-Dev/gocast/blob/6d0c3cc740995f7205a6d312bb9cab42d7305be0/api/users.go#L143-L144

2025-02-26 15:21 UTC, merged