Implement Chat Endpoints
joschahenningsen/TUM-Live pull request #1288
Opened 2024-01-04 17:56 UTC by mo-cmyk

### Motivation and Context
This implements Endpoints for Chats, Reactions and Chat replies to solve https://github.com/TUM-Dev/gocast_mobile/issues/91

### Description
The following endpoints are included in this PR

- [x] Get Chat Messages
- [x] Create Chat Messages
- [x] Post and Patch Reaction to a Message 
- [x] Delete a Reaction to a Message 
- [x] Post Replies to Messages
- [x] Mark Questions as Resolved
- [x] Mark Questions as Unresolved

2024-01-07 22:34 UTC, carlobortolan requested changes
Look (mostly) good to me :+1: 
The endpoints work great.
However, there are some unhandled edge-cases - mainly for malformed request messages (e.g., missing streamID, message etc.) and for streams (/stream's courses) with disabled chats (see `stream.chat_enabled`, `course.chat_enabled`, `course.moderated_chat_enabled` and `course.vod_chat_enabled`)

Also one question regarding the request messages:
Do we need to send the chatID in each request (other than the GetChatMessages and PostChatMessages endpoint) or wouldn't it be enough to send the chatID?

2024-01-07 22:34 UTC, carlobortolan commented on api_v2/api_v2.proto
> +  uint64 chatID = 3;
Why do you need a `streamID` and `chatID` to post a reaction to a chat message? (Wouldn't the `chatID` be enough?)

2024-01-07 22:34 UTC, carlobortolan commented on api_v2/api_v2.proto
> +}
See message above (What do we need the `streamID` for?)

2024-01-07 22:34 UTC, carlobortolan commented on api_v2/api_v2.proto
> +  uint64 chatID = 3;
See message above (What do we need the `streamID` for?)

2024-01-07 22:34 UTC, carlobortolan commented on api_v2/api_v2.proto
> +  uint64 chatID = 2;
See message above (What do we need the `streamID` for?)

2024-01-07 22:34 UTC, carlobortolan commented on api_v2/api_v2.proto
> +  uint64 chatID = 2;
See message above (What do we need the `streamID` for?)

2024-01-07 22:34 UTC, carlobortolan commented on go.work
idk why, but this code makes the remote deployment crash once you create a PR to `dev`, so it's better to leave it as:
```go
go 1.21

use (
```

2024-01-07 22:34 UTC, carlobortolan commented on go.mod
idk why, but this code makes the remote deployment crash once you create a PR to `dev`, so it's better to leave it as:
```go
go 1.21

use (
```

2024-01-07 22:34 UTC, carlobortolan commented on api_v2/docs/index.html
Use the manually generated doc (./swagger.json) instead.
You can use the following file which is the old swagger.json including the new chat endpoints:
[swagger.json](https://github.com/TUM-Dev/gocast/files/13855052/swagger.json)

2024-01-07 22:34 UTC, carlobortolan commented on api_v2/stream.go
Some edge cases which currently do not return the expected status code:

+ Return [3 INVALID_ARGUMENT] instead of [5 NOT_FOUND] when request is missing streamID (`streamID==0`).
See [this example](https://www.postman.com/tumdev/workspace/team-workspace/grpc-example/659b1f995188ca95c7bce773).

+ Return [7 PERMISSION_DENIED] instead of [0 OK] in the following cases:
   + when chats are disabled for stream (`stream.chat_enabled==false`)
   + when stream is VoD and course has (`chat_enabled==false` && `moderated_chat_enabled==false`) || `vod_chat_enabled==false`)
   + when stream is live and course has `chat_enabled==false` &&  `moderated_chat_enabled==false`
See [this example](https://www.postman.com/tumdev/workspace/team-workspace/grpc-example/659b20fbeab756946a1e66df).

2024-01-08 13:33 UTC, mo-cmyk commented on api_v2/api_v2.proto
> +  uint64 chatID = 3;
To keep routes consistent but can be changed also

2024-01-12 12:52 UTC, carlobortolan requested changes

2024-01-12 12:52 UTC, carlobortolan commented on go.mod
> +toolchain go1.21.5
Remove also `toolchain go1.21.5`

2024-01-12 12:52 UTC, carlobortolan commented on go.work
> +
Remove also these lines:
```Go
toolchain go1.21.5

```

2024-01-12 12:59 UTC, carlobortolan approved these changes
Looks good to me :+1:

2024-01-12 12:59 UTC, merged