adding shortcuts on the video player buttons controltext
joschahenningsen/TUM-Live pull request #1317
Opened 2024-01-22 13:21 UTC by barisgul15

### Motivation and Context

fixes #1289

### Description

1-shortcuts are added to video players buttons. before: play -> after play (k)
2-keyboard shortcuts should be added to the menu under keyboard icon

### Steps for Testing

1. Log in
2. Navigate to a Video
3. Check the text appears when the mouse is on one of the player buttons
4. Open menu at the home page and click keyboard icon

### Screenshots

2024-04-22 12:58 UTC, SebiWrn requested changes, later dismissed
You shouldn't create js files directly but rather create Typescript files and include them into the bundles so they get optimized. Please move your js code to the correct typescript files

2024-09-23 14:57 UTC, SebiWrn commented
If you still want to merge this PR please reopen the PR and fix the issues

2025-02-28 08:19 UTC, joschahenningsen commented on web/template/home.gohtml
> +                        <nav class="d-grid gap-3 font-light" x-data="{showPopup: false}">
Are we sure we want this on every page and not just on the watch page? The shortcuts are only relevant there, right?

2025-02-28 08:19 UTC, joschahenningsen commented on web/template/home.gohtml
> +                            <div x-ref="keyboardShortcutsPopup" x-show="showPopup" class="tum-live-popup-container overlay" @keydown.escape.window="showPopup=false;">
I think this should be cloaked: https://alpinejs.dev/directives/cloak

2025-03-03 16:28 UTC, karjo24 commented on web/template/home.gohtml
> +                        <nav class="d-grid gap-3 font-light" x-data="{showPopup: false}">
This was only a rewrite of the existing, closed PR to better fit our codebase so it can be discussed again. Having said that, I agree. The question is where to incorporate this into the watch page? I'm not too happy about any  and the menu where it currently is incorporated isn't included in the watch page.

2026-04-19 10:15 UTC, alexanderstephan commented
Hi all, I tried to integrate it in the action bar on the watch page. What do you think?
<img width="1213" height="664" alt="image" src="https://github.com/user-attachments/assets/5610a0fa-a2c5-4642-bf70-ba5a7e040656" />
I also changed it to a column layout for more readability.

2026-04-19 20:56 UTC, kordianbruck commented
I like it a lot :tada:

2026-04-19 20:57 UTC, kordianbruck approved these changes

2026-04-20 17:21 UTC, merged