Enh/update videojs
joschahenningsen/TUM-Live pull request #1318
Opened 2024-01-23 18:55 UTC by SebiWrn

### Motivation and Context
Video.js has a new major version and we should update it for security and functionality purposes.

### Description
Updated Video.js and fixed some new errors that occured due to a new system on the video.js side. Some workarounds because Video.js isn't really compatible to TypeScript, but only to JavaScript.

2024-01-23 19:33 UTC, SebiWrn commented
Testserver is online at https://1318.test.live.mm.rbg.tum.de/

2024-01-24 21:17 UTC, meandaD submitted a review, later dismissed
It works great! Thank you, it feels so good not to see warnings about vulnerabilities all the time.
But I would suggest to wait for another approval review, since this looks not like a minor change and may have side effects that I'm not awared of...

2024-01-24 21:53 UTC, meandaD requested changes
The upgrade doesn't seem quite perfect yet. I get these errors during compiling:
<details><summary>Compile errors</summary>
  modules by path ./ts/*.ts 53.3 KiB
    modules with errors 34.4 KiB [errors]
      ./ts/TUMLiveVjs.ts 20.8 KiB [built] [code generated] [2 errors]
      + 3 modules
    + 5 modules
  modules by path ./ts/entry/*.ts 682 bytes
    ./ts/entry/video.ts 388 bytes [built] [code generated]
    ./ts/entry/interactions.ts 294 bytes [built] [code generated]
  modules by path ./ts/components/*.ts 12.4 KiB
    ./ts/components/video-sections.ts 1.91 KiB [built] [code generated]
    ./ts/components/chat.ts 10.5 KiB [built] [code generated] [1 error]
  ./ts/video/watchers.ts 831 bytes [built] [code generated] [1 error]

ERROR in /home/dyr/gocast/web/ts/components/chat.ts
./ts/components/chat.ts 10:9-22
[tsl] ERROR in /home/dyr/gocast/web/ts/components/chat.ts(10,10)
      TS2614: Module '"video.js"' has no exported member 'VideoJsPlayer'. Did you mean to use 'import VideoJsPlayer from "video.js"' instead
?
 @ ./ts/entry/interactions.ts 2:0-35 2:0-35

ERROR in /home/dyr/gocast/web/ts/TUMLiveVjs.ts
./ts/TUMLiveVjs.ts 3:18-31
[tsl] ERROR in /home/dyr/gocast/web/ts/TUMLiveVjs.ts(3,19)
      TS2614: Module '"video.js"' has no exported member 'VideoJsPlayer'. Did you mean to use 'import VideoJsPlayer from "video.js"' instead
?
 @ ./ts/entry/video.ts 3:0-30 3:0-30

ERROR in /home/dyr/gocast/web/ts/TUMLiveVjs.ts
./ts/TUMLiveVjs.ts 237:41-47
[tsl] ERROR in /home/dyr/gocast/web/ts/TUMLiveVjs.ts(237,42)
      TS2339: Property 'extend' does not exist on type 'typeof videojs'.
 @ ./ts/entry/video.ts 3:0-30 3:0-30

ERROR in /home/dyr/gocast/web/ts/seekbar-highlights.ts
./ts/seekbar-highlights.ts 3:9-22
[tsl] ERROR in /home/dyr/gocast/web/ts/seekbar-highlights.ts(3,10)
      TS2614: Module '"video.js"' has no exported member 'VideoJsPlayer'. Did you mean to use 'import VideoJsPlayer from "video.js"' instead
?
 @ ./ts/watch.ts 134:0-69 134:0-69 134:0-69
 @ ./ts/entry/video.ts 4:0-25 4:0-25

ERROR in /home/dyr/gocast/web/ts/hotkeys.ts
./ts/hotkeys.ts 24:58-71
[tsl] ERROR in /home/dyr/gocast/web/ts/hotkeys.ts(24,59)
      TS2694: Namespace 'videojs' has no exported member 'KeyboardEvent'.
 @ ./ts/TUMLiveVjs.ts 6:0-42 130:21-34
 @ ./ts/entry/video.ts 3:0-30 3:0-30

ERROR in /home/dyr/gocast/web/ts/hotkeys.ts
./ts/hotkeys.ts 34:30-41
[tsl] ERROR in /home/dyr/gocast/web/ts/hotkeys.ts(34,31)
ERROR in /home/dyr/gocast/web/ts/video/watchers.ts
./ts/video/watchers.ts 1:9-22
[tsl] ERROR in /home/dyr/gocast/web/ts/video/watchers.ts(1,10)
      TS2614: Module '"video.js"' has no exported member 'VideoJsPlayer'. Did you mean to use 'import VideoJsPlayer from "video.js"' instead
?
 @ ./ts/components/video-sections.ts 3:0-56 14:12-31
 @ ./ts/entry/video.ts 8:0-45 8:0-45

9 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.89.0 compiled with 9 errors in 1989 ms
</details>

---
The player stucks when I try to hover over the progress bar. This can be reproduced in the testserver link.

2024-01-25 11:27 UTC, SebiWrn commented
I think the build error is only locally on your system because some files aren't updated, because VideoJsPlayer isn't used in any file anymore.

2024-01-25 12:18 UTC, meandaD commented
> I think the build error is only locally on your system because some files aren't updated, because VideoJsPlayer isn't used in any file anymore.

That's possible, I will do more checks locally. But the problem does occur on [](https://1318.test.live.mm.rbg.tum.de/). Maybe the build environment for test servers also has the same problem as my environment?

2024-01-29 11:38 UTC, SebiWrn commented
Now I have the same problem locally, never had it before, I'll have a look into it

2025-01-10 14:50 UTC, kordianbruck commented
Whats the progress on this request? Any luck with the investigation?

2025-12-05 17:43 UTC, closed without merging