Fixed non working admin download
joschahenningsen/TUM-Live pull request #1388
Opened 2024-10-20 11:06 UTC by SebiWrn

### Motivation and Context
Admins should be able to download VODs from the admin panel.

### Description
Now every VOD that is displayed on the admin panel is already signed with a corresponding jwt token which allows downloading of the vods.

2024-10-21 13:01 UTC, SebiWrn commented
Some more changes than expected because worker was also reverted to last working version of worker so the latest version of the worker is also functional. Everything in the worker/ directory is just reverting changes.

2024-11-02 18:40 UTC, joschahenningsen requested changes
There are a lot of unrelated changes, can you clean that up a bit?

2024-11-04 21:30 UTC, SebiWrn commented
Sorry for that, now it should be cleaned up

2024-11-08 17:44 UTC, joschahenningsen approved these changes

2024-11-10 08:21 UTC, merged