Test course feature for lecturers
joschahenningsen/TUM-Live pull request #1425
Opened 2024-12-18 15:34 UTC by carlobortolan

### Motivation and Context
This is one possible approach to solve #1418.
While this approach is not optimal, as we need to "reserve" special values for test courses, it is relatively simple and builds on top of the existing code in comparison to more complex approaches (e.g., updating the current course model & table to include a `isTestCourse` attribute or adding a completely new test course model).

### Description
- Internally, test courses are handled just like regular courses but belong to a special "test-semester" (where the course's term equals `Test`).
- Updated semester API endpoint and course DAO methods to include an optional `includeTestSemester` flag, which defaults to false. This allows the endpoint & method to return the same information as before (all normal courses), and only if the flag is set, also include the test courses.
- Updated all current occurrences of the semester-fetching (e.g., on the start page, search page, and admin page) accordingly so that the test semesters and courses are not included there. 

### Steps for Testing
Prerequisites:
- 1 Lecturer
- 1 Student

1. Log in as a lecturer
2. Go to the admin panel and press on `+ Create Test Course` to create a new test course
3. The test course should now appear after reloading the page
4. Log out and log in as another user
5. Check that the previously created test course is not visible anywhere and that the semesters don't include the test semester

### Screenshots
How to create a test course:
![image](https://github.com/user-attachments/assets/55e34900-c4df-4150-bf3b-f51d048ff6fd)

How an Admin sees all test courses: 
![image](https://github.com/user-attachments/assets/788701e3-908d-4a72-a4e2-0ddebfb86d44)

2025-01-11 13:18 UTC, SebiWrn requested changes

2025-01-11 13:18 UTC, SebiWrn commented on api/courses.go
> +	_, err := r.StreamsDao.CreateOrGetTestCourse(tumLiveContext.User)
Should every user be able to create a test course? If every student can create a test course, they could possibly fill up the entire disk just by streaming nonsense

2025-01-11 13:18 UTC, SebiWrn commented on dao/streams.go
> +		Name:         user.GetPreferredName() + "'s Test Course",
Maybe we should have a fallback if the users preferred name is empty

2025-01-11 13:18 UTC, SebiWrn commented on web/admin.go
> +	semesters := r.CoursesDao.GetAvailableSemesters(c, false)
Should we allow to see stats of the test courses? Maybe with that users could also test this stats functionality?

2025-01-11 13:18 UTC, SebiWrn commented on web/admin.go
> +
Duplicate with line 284, this should be another function so the test course check can be adjusted if we change the implementation of test courses

2025-01-12 00:05 UTC, carlobortolan commented on api/courses.go
> +	_, err := r.StreamsDao.CreateOrGetTestCourse(tumLiveContext.User)
Only lecturers should be allowed to create test courses, but this should already be the case here, no?

See:
https://github.com/TUM-Dev/gocast/blob/68e73553a9a80e8d3e353f0e3fea5bfbf8eff0a1/api/courses.go#L51
and:
https://github.com/TUM-Dev/gocast/blob/68e73553a9a80e8d3e353f0e3fea5bfbf8eff0a1/api/courses.go#L54

2025-01-12 00:05 UTC, carlobortolan commented on dao/streams.go
> +		Name:         user.GetPreferredName() + "'s Test Course",
Thanks for pointing that out; fixed it in the latest commit.

2025-01-12 00:07 UTC, carlobortolan commented on web/admin.go
> +
Done :white_check_mark:

2025-01-12 00:08 UTC, carlobortolan commented on web/admin.go
> +	semesters := r.CoursesDao.GetAvailableSemesters(c, false)
I don't think there should be any problem if we allow lecturers to see stats for test courses; updated it in my latest commit :+1:

2025-01-27 13:40 UTC, SebiWrn commented on api/courses.go
> +	_, err := r.StreamsDao.CreateOrGetTestCourse(tumLiveContext.User)
Oh sorry I didn't look into the path mapping. Yes it's the case

2025-01-27 13:45 UTC, SebiWrn approved these changes
Looks good :)

2025-01-27 13:53 UTC, merged