Hamburger Menu
joschahenningsen/TUM-Live pull request #239
Opened 2022-01-20 10:16 UTC by MatthiasReumann

#237

2022-01-20 22:46 UTC, alexanderstephan requested changes
Looks good to me codewise, design wise I also really like this!

When a played around with it, I noticed a couple minor things:
I noticed that somehow there is a lot free space in the menu in my browser, see the image blow. Resolution is 637x874 in this example.

<img src="https://user-images.githubusercontent.com/30267166/150431342-9f52b2a6-aeba-49b3-92ec-a2caddf6410c.png" width="300">
Maybe we can reduce the right margin? We could also think about putting the dark theme and GitHub icon directly below the other menu items, I guess.

I also think that in light mode, the menu items could be almost black instead of grey. I have a hard time reading the text here.

I noticed that the "Login" spacing is different on my Honor 6x Android 7 Phone on Firefox. I can't reproduce it on my Desktop though. So not sure, if this easily fixable or even a problem on my end.
<img src="https://user-images.githubusercontent.com/30267166/150432851-9935f851-a66d-43a2-9bda-d550dbe8678a.png" width="300">

2022-01-22 19:44 UTC, joschahenningsen commented on web/template/header.gohtml
> +                            <span>Login</span>
```suggestion
                            <span class="ml-3">Login</span>
```

2022-01-22 19:44 UTC, joschahenningsen commented on web/template/header.gohtml
> +                            <span>Login</span>
This should fix @alexanderstephan s observation

2022-01-22 19:46 UTC, joschahenningsen commented
Other than what @alexanderstephan pointed out, this looks great! I agree that there is quite a bit of space here, but I don't mind.

2022-01-24 08:02 UTC, MatthiasReumann commented
> Looks good to me codewise, design wise I also really like this!
> 
> When a played around with it, I noticed a couple minor things: I noticed that somehow there is a lot free space in the menu in my browser, see the image blow. Resolution is 637x874 in this example.
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/30267166/150431342-9f52b2a6-aeba-49b3-92ec-a2caddf6410c.png">
> 
> Maybe we can reduce the right margin? We could also think about putting the dark theme and GitHub icon directly below the other menu items, I guess.
> I also think that in light mode, the menu items could be almost black instead of grey. I have a hard time reading the text here.
> 
> I noticed that the "Login" spacing is different on my Honor 6x Android 7 Phone on Firefox. I can't reproduce it on my Desktop though. So not sure, if this easily fixable or even a problem on my end. <img alt="" width="300" src="https://user-images.githubusercontent.com/30267166/150432851-9935f851-a66d-43a2-9bda-d550dbe8678a.png">

- Fixed the Login bug (Thanks @joschahenningsen!) 
- Changed the dark-mode button to a toggle thingy 
- Moved the GitHub and toggle button up
- Light mode text black

2022-01-24 09:41 UTC, joschahenningsen approved these changes
Looks super clean :fire:

2022-01-24 11:55 UTC, alexanderstephan approved these changes
Looks awesome, I also really like the addition of the dark mode toggle! :fire: Maybe this means we should close https://github.com/joschahenningsen/TUM-Live/pull/134?

2022-01-24 11:55 UTC, merged