Delete Course Button
joschahenningsen/TUM-Live pull request #282
Opened 2022-02-01 14:43 UTC by MatthiasReumann

- Closes #228 

I've noticed that after a course is deleted it is still shown on the left menu (It is however deleted). Any idea why this could be the case? (Caching?)

2022-02-01 16:08 UTC, joschahenningsen commented
Could be caching, yeah. I usually call `Cache.Clear()` after significant changes like this one. Does that help?

2022-02-03 18:09 UTC, MatthiasReumann commented
> Could be caching, yeah. I usually call `Cache.Clear()` after significant changes like this one. Does that help?

Yup. Solved it, thanks!

2022-02-04 07:59 UTC, joschahenningsen requested changes
Looks good, just a thought

2022-02-04 07:59 UTC, joschahenningsen commented on api/courses.go
> +	fmt.Println(*tumLiveContext.Course)
```suggestion
```

2022-02-04 07:59 UTC, joschahenningsen commented on api/courses.go
> +	fmt.Println(*tumLiveContext.Course)
This print statement doesn't seem to add much value. But a little
```go
log.WithFields(log.Fields{
	"user": tumLiveContext.User.ID,
	"course": tumLiveContext.Course.ID,
}).Info("Delete Course Called")
```
Would be nice

2022-02-07 07:47 UTC, joschahenningsen approved these changes
Sorry for the late review, looks good, thanks!

2022-02-07 07:48 UTC, merged