Add error pages
joschahenningsen/TUM-Live pull request #324
Opened 2022-03-14 10:06 UTC by joschahenningsen

Resolves #322 

This Pr adds some error pages:
- 404 catch all
- 404 course not found
- 404 stream not found
- 403 stream/course access not allowed
- 403 admin access not allowed

https://user-images.githubusercontent.com/44805696/158150529-b6deb27e-9ca4-43da-a641-67c960fb060c.mp4

2022-03-14 10:06 UTC, joschahenningsen commented on web/template/error.gohtml
> +            background-image: url('https://media2.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.gif');
Let's see if this URL ever changes

2022-03-15 14:58 UTC, alexanderstephan requested changes
Exactly what I imagined, really nice! :partying_face: 

I only noticed that some comments for exported methods might be needed, and that a copy-paste problem. Otherwise the code changes look really clean. :+1:

2022-03-15 14:58 UTC, alexanderstephan commented on dao/courses.go
>  func GetCourseByShortLink(link string) (model.Course, error) {
This should probably have a comment.

2022-03-15 14:58 UTC, alexanderstephan commented on web/template/error.gohtml
> +            background-image: url('https://media2.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.gif');
If it breaks, it's probably time for a new image. :joy:

2022-03-15 14:58 UTC, alexanderstephan commented on tools/middlewares.go
> +	ForbiddenCourseAccess = "You don't have permissions to access this stream. " +
```suggestion
	ForbiddenCourseAccess = "You don't have permissions to access this course. " +
```

2022-03-15 18:06 UTC, alexanderstephan approved these changes
Looks good to me! :100:

2022-03-15 18:07 UTC, merged