Fix: Different speeds don't work on Firefox mobile
joschahenningsen/TUM-Live pull request #451
Opened 2022-05-12 07:14 UTC by just-max

Fixes #430 

Also removed (declared) dependency on `videojs-contrib-hls`, since HLS support is already built into VideoJS 7. As far as I can tell nothing is using the package, but correct me if I missed something.

2022-05-12 07:30 UTC, joschahenningsen requested changes
Amazing, thanks a lot for your engagement here, hit us up if you want to do this on a regular basis!

2022-05-12 07:30 UTC, joschahenningsen commented on web/package.json
> -    "videojs-contrib-hls": "^5.15.0",
can you also sync the package-lock.json?

2022-05-12 07:30 UTC, joschahenningsen commented on web/template/admin/lecture-cut.gohtml
> +            <video-js
I was thinking way to complicated here :smile: where did you find this fix? We should definitely do some testing as to how browsers react to this, but looks good!

2022-05-12 15:26 UTC, just-max commented
> where did you find this fix

the stream itself worked fine in the videojs demo, so from there transplanting things into the demo until it broke again :) the videojs [docs](https://videojs.com/guides/setup/#creating-a-player) do mention it, but of course I only saw that afterwards...

> hit us up if you want to do this on a regular basis

sure, depending on how busy the semester gets :<

2022-05-16 08:32 UTC, joschahenningsen approved these changes
Looks good! Thanks :)

2022-05-16 08:32 UTC, merged