Fix: Order of VoDs Is Reversed When Not Logged-In
joschahenningsen/TUM-Live pull request #486
Opened 2022-05-29 20:53 UTC by just-max

Fixes #485

2022-05-31 17:20 UTC, alexanderstephan requested changes
Nice addition, just some minor note that could be done before merge.

2022-05-31 17:20 UTC, alexanderstephan commented on web/template/vod_course_list.gohtml
> +    {{if and $user $course.HasRecordings}}
Good catch, can you also remove the corresponding `User` field from `CoursePageData`? I don't think it's used anywhere else.

2022-06-01 13:40 UTC, just-max commented on web/template/vod_course_list.gohtml
> +    {{if and $user $course.HasRecordings}}
Removed.

2022-06-01 14:30 UTC, alexanderstephan approved these changes
Thanks! 👍

2022-06-01 14:30 UTC, merged