Add null checks for user to for course overview and watch pages.
joschahenningsen/TUM-Live pull request #518
Opened 2022-06-05 20:17 UTC by just-max

Fixes #517.

2022-06-05 21:06 UTC, alexanderstephan requested changes
Thanks for fixing this! I think I saw this somewhere on Zulip today.
Not adding the parentheses causes this to fail for logged in users now. The result of the `or` function should be an argument that is passed to the `and` function so it needs parentheses. The syntax can be a bit confusing...

2022-06-05 21:06 UTC, alexanderstephan commented on web/template/watch.gohtml
> +                    {{if and $user or ($user.IsAdminOfCourse .IndexData.TUMLiveContext.Course) .IndexData.IsAdmin}}
```suggestion
                    {{if and $user (or ($user.IsAdminOfCourse .IndexData.TUMLiveContext.Course) .IndexData.IsAdmin)}}
```

2022-06-05 21:06 UTC, alexanderstephan commented on web/template/course-overview.gohtml
> +        {{if and $user or ($user.IsAdminOfCourse .IndexData.TUMLiveContext.Course) .IndexData.IsAdmin}}
```suggestion
        {{if and $user (or ($user.IsAdminOfCourse .IndexData.TUMLiveContext.Course) .IndexData.IsAdmin)}}
```

2022-06-06 09:05 UTC, joschahenningsen commented
Thanks for taking a look here! I'll close this as it's fixed in 65a633751e8c49fd97649428f152e641e52ce352 though :)

2022-06-06 09:05 UTC, closed without merging