Include Timestamp in URL
joschahenningsen/TUM-Live pull request #633
Opened 2022-08-11 05:18 UTC by MatthiasReumann

## Changes
- Add `getQueryParam` function to `global.ts`
- Set the timestamp of the player for the given parameter in the `watchProgress` handler.

## Further Information
The current implementation ignores the user's video progress if query parameter `t` is set. (`if ... else`).

2022-08-11 15:33 UTC, just-max requested changes
Thanks, just what I wanted :heart_eyes:

2022-08-11 15:33 UTC, just-max commented on web/ts/global.ts
> +    return undefined;
`URL` can do this directly
```suggestion
    return new URL(window.location.href).searchParams.get(name) ?? undefined;
```

2022-08-11 15:33 UTC, just-max commented on web/ts/TUMLiveVjs.ts
> +            player.currentTime(Number(queryT));
This should probably include the same special handling as for iOS, which can be encapsulated in a function to be called from both places.

2022-08-12 04:38 UTC, MatthiasReumann commented on web/ts/global.ts
> +    return undefined;
Thanks, that's great!

2022-08-12 15:16 UTC, just-max approved these changes
Thanks, works nicely!

2022-08-12 15:16 UTC, just-max commented on web/template/watch.gohtml
> +    watch.watchProgress({{$stream.Model.ID}}, {{ .Progress.Progress }}, {{.IndexData.TUMLiveContext.User}});
```suggestion
    watch.watchProgress({{$stream.Model.ID}}, {{ .Progress.Progress }}, {{not (empty .IndexData.TUMLiveContext.User)}});
```

2022-08-16 13:42 UTC, just-max approved these changes
Looks good, thanks for implementing this!

2022-08-16 20:26 UTC, alexanderstephan approved these changes
Cool feature! :100: Code also looks good to me :+1:

2022-08-16 20:28 UTC, merged

2022-08-17 10:30 UTC, joschahenningsen commented
Amazing, now I can share https://live.rbg.tum.de/w/it-sec/7105?t=4411 :heart_eyes:

2022-11-03 14:15 UTC, just-max commented on web/ts/TUMLiveVjs.ts
> +            return true;
In relation to #752 : this doesn't look right. From what I can tell, the `return true;` is meant to be used to update the value of `iOSReady` in `watchProgress`. Returning it from the callback doesn't do that. Thus, `iOSReady` is always false and the player keeps settings the current time (in the case of #752 , to the end of the video). Can't test if that's actually the problem right now.