Remove Course.LiveEnabled
joschahenningsen/TUM-Live pull request #636
Opened 2022-08-11 07:57 UTC by MatthiasReumann

## Changes 
- Closes #391 
- Updates testdata
- Eliminates `LiveEnabled` from all places

## Further information 
SQL drop column command:
```sql
ALTER TABLE courses DROP COLUMN live_enabled;
```

2022-08-11 08:48 UTC, joschahenningsen commented
> `ALTER TABLE courses DROP COLUMN live_enabled;`

This could be a [migragtion](https://github.com/joschahenningsen/TUM-Live/blob/dev/dao/migrations/202207240.go)

2022-08-11 09:02 UTC, MatthiasReumann commented
> > `ALTER TABLE courses DROP COLUMN live_enabled;`
> 
> This could be a [migragtion](https://github.com/joschahenningsen/TUM-Live/blob/dev/dao/migrations/202207240.go)

I've added the migration. I hope I got the naming right 😅 How do I make sure that the migrations executes - or in other words - where do I call the migration?

2022-08-11 09:20 UTC, joschahenningsen commented
You can reference it here https://github.com/joschahenningsen/TUM-Live/blob/f80d12b754a30effed3f7bfc26533187351790d7/dao/migrator.go#L34 :)

2022-08-15 11:34 UTC, joschahenningsen approved these changes

2022-08-15 11:38 UTC, joschahenningsen requested changes
I think `course.StreamEnabled` becomes `streamCtx.stream` after sending the request to the worker. 

https://github.com/joschahenningsen/TUM-Live/blob/fa9bfbf2c0a13dc9446a2325efb204d99cfea31a/worker/worker/request_handlers.go#L433

This should also be removed along with the logic for just recording without streaming.

2022-08-16 13:35 UTC, MatthiasReumann commented
> I think `course.StreamEnabled` becomes `streamCtx.stream` after sending the request to the worker.
> 
> https://github.com/joschahenningsen/TUM-Live/blob/fa9bfbf2c0a13dc9446a2325efb204d99cfea31a/worker/worker/request_handlers.go#L433
> 
> This should also be removed along with the logic for just recording without streaming.

Thanks! 

> the logic for just recording without streaming.

Thanks! How about the `PublishStream` attribute in the `StreamRequest`? I guess that should be deleted too.

2022-08-17 10:35 UTC, joschahenningsen commented
> How about the PublishStream attribute in the StreamRequest?

Yup that should be removable as well then.

Am Di., 16. Aug. 2022 um 15:35 Uhr schrieb matthias <
***@***.***>:

> I think course.StreamEnabled becomes streamCtx.stream after sending the
> request to the worker.
>
>
> https://github.com/joschahenningsen/TUM-Live/blob/fa9bfbf2c0a13dc9446a2325efb204d99cfea31a/worker/worker/request_handlers.go#L433
>
> This should also be removed along with the logic for just recording
> without streaming.
>
> Thanks!
>
> the logic for just recording without streaming.
>
> Thanks! How about the PublishStream attribute in the StreamRequest? I
> guess that should be deleted too.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/joschahenningsen/TUM-Live/pull/636#issuecomment-1216648389>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKV24QGBA6CPV3WX3UJ3GZLVZOKLDANCNFSM56HGNXTQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-09-16 08:06 UTC, joschahenningsen approved these changes

2022-09-16 08:06 UTC, joschahenningsen commented on worker/worker/request_handlers.go
>  	//only record
```suggestion
```

2022-09-16 08:06 UTC, merged