Influxdb viewer stats
joschahenningsen/TUM-Live pull request #696
Opened 2022-10-02 15:51 UTC by mono424

Pushing viewer stats into the influxdb instead of mysql.
 
To test:
- setup a local influxdb
- retrieve api token from web interface (Load Data > API Token)
- add api token to `config.yaml`

2022-10-03 11:09 UTC, joschahenningsen requested changes
Looks good so far! The next step would be to get the stats back from influxdb to display them (e.g. at `/admin/course/123/stats`). 
Are you familiar with the [flux](https://docs.influxdata.com/influxdb/v2.4/query-data/flux) query language? If you want I can write a few useful queries for you to use :)

2022-10-03 11:09 UTC, joschahenningsen commented on tools/stats/stats.go
> +		liveStats: client.WriteAPIBlocking("rbg", "live_stats"),
This should either be non blocking or writing the stats has to happen in a separate go routine. I prefer the first option.

2022-10-03 11:09 UTC, joschahenningsen commented on api/chat.go
> +					if err := stats.Client.AddStreamStat(fmt.Sprintf("%d", s.CourseID), stat); err != nil {
Here the live viewers are counted. Can we also add a point for every vod view? (https://github.com/joschahenningsen/TUM-Live/blob/5aa33d394ed3b639e703fcdfc9eac4521bee5bd6/api/chat.go#L634)

2022-10-03 11:09 UTC, joschahenningsen commented on api/chat.go
> +					if err := stats.Client.AddStreamStat(fmt.Sprintf("%d", s.CourseID), stat); err != nil {
Also the `AddVodView` dao stuff can then be removed.

2022-10-03 13:38 UTC, mono424 commented
> Looks good so far! The next step would be to get the stats back from influxdb to display them (e.g. at `/admin/course/123/stats`). Are you familiar with the [flux](https://docs.influxdata.com/influxdb/v2.4/query-data/flux) query language? If you want I can write a few useful queries for you to use :)

Not yet, but I love to look into that. You would still appreciate the few useful queries 💯

2022-10-04 07:38 UTC, joschahenningsen commented
Let's start with this for testing :)

### Live viewers for a course:
```flux
from(bucket: "live_stats")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "viewers")
  |> filter(fn: (r) => r["course"] == "224")
  |> filter(fn: (r) => r["live"] == "true")
  |> group(columns: ["stream"])
  |> max()
  |> group()
  |> aggregateWindow(every: 1d, fn: median, createEmpty: false)
```

Produces [2022-10-04_09 36_influxdb_data.csv](https://github.com/joschahenningsen/TUM-Live/files/9703685/2022-10-04_09.36_influxdb_data.csv)

Which looks like this:

![image](https://user-images.githubusercontent.com/44805696/193761621-3aa84128-59fa-4a47-b167-bd9c0e73c79e.png)

2022-12-03 12:15 UTC, joschahenningsen requested changes

2022-12-03 12:15 UTC, joschahenningsen commented on web/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
can this be deleted?

2022-12-03 12:15 UTC, joschahenningsen commented on .idea/runConfigurations/build_dev.xml
> +    <package-manager value="yarn" />
this can be reverted

2022-12-03 12:15 UTC, joschahenningsen commented on dao/statistics.go
>  package dao
Can you regenerate the mock dao please?

2022-12-03 12:15 UTC, joschahenningsen commented on dao/statistics.go
>  func (d statisticsDao) GetCourseNumStudents(courseID uint) (int64, error) {
This could now be part of the course dao. Then we might delete this file.

2023-09-20 15:59 UTC, joschahenningsen commented
T'm afraid this needs to be closed. Sorry for letting this go stale, I suppose the best way to move forward here is integrate our grafana stack here at some point.

2023-09-20 15:59 UTC, closed without merging