allow deselecting lecture halls in calendar
joschahenningsen/TUM-Live pull request #735
Opened 2022-10-20 12:50 UTC by joschahenningsen

### Motivation and Context

To have a quick glance about the events that are in a certain lecture hall it would be helpful if we were able to filter the events in the calendar.
fixes #732 

### Description

This PR adds a checkbox for each lecture hall below the calendar. If a checkbox is checked we pass the id to the api which then includes that lecture hall in the result. The changes (logic wise) are done in SQL.

### Steps for Testing

Prerequisites:
- Lecturers
- An admin

1. generate events for different courses in different lecture halls.
2. view the schedule as lectuer and verify that 
  2.1 filtering by lecture hall works.
  2.2 The lecturer only sees their events.  
4. test that filtering also works for admins.

2022-10-21 20:21 UTC, alexanderstephan requested changes
Cool feature! I tested all the listed steps and everything works flawlessly. :+1: 

I noticed only two small potential problems.
- Checkbox text is not readable presumable a missing CSS class. Or maybe there is a problem with my setup right now. :thinking: 
![grafik](https://user-images.githubusercontent.com/30267166/197281573-ec85ca1d-4d54-47e5-8975-4b59b1a4e3f4.png)

- After updating the filters there are always to identical `GET` requests. Is this intended? I noticed small very short flickering, maybe this is related? I did not have too much time to look into it, but want to have it mentioned here. :stuck_out_tongue:
![grafik](https://user-images.githubusercontent.com/30267166/197282345-6a7ac469-f66b-4504-8c06-efa89f88d218.png)

2022-10-21 21:48 UTC, joschahenningsen commented
I pushed a few tiny fixes, this is what it looks like on my end now: 

https://user-images.githubusercontent.com/44805696/197293618-63b5ddf1-c97f-495c-8634-7036d2e81fbf.mp4

I couldn't find out why your url didn't change, can you verify the latest commit?

2022-10-21 21:49 UTC, joschahenningsen commented
> I noticed small very short flickering

I think the fullCalendar needs some time to render the events unfortunately :/

2022-10-21 22:02 UTC, alexanderstephan commented
> I think the fullCalendar needs some time to render the events unfortunately :/

Hm, not really in issue, but might be worth to look whether there is an issue for this for fullCalendar.

> I pushed a few tiny fixes, this is what it looks like on my end now:

Looks the same for me, looks good now!

> I couldn't find out why your url didn't change, can you verify the latest commit?

I mean the URL did change after editing, but the request is sent twice. I recorded another gif to make sure we mean the same thing. Do you also have this?

![Peek 2022-10-22 00-00](https://user-images.githubusercontent.com/30267166/197294960-664fb5a4-6791-49d1-a525-5ddbc2e2ce30.gif)

2022-10-22 08:43 UTC, joschahenningsen commented
@alexanderstephan nice catch! Apparently `AddEventSource` already triggers `RefetchEventSources` internally so the call was redundant.

2022-10-22 22:36 UTC, alexanderstephan requested changes
Looks good! I just found one more minor bug.

2022-10-22 22:36 UTC, alexanderstephan commented on api/lecture_halls.go
> +	lectureHallsStr := strings.Split(c.Request.Form.Get("lecturehalls"), ",")
One last thing I noticed: This does not work if all lecture halls are deselected, resulting in the following error:
<img width="547" alt="grafik" src="https://user-images.githubusercontent.com/30267166/197364655-eb2415fe-46da-430b-9cdc-808830c5d83a.png">

2022-10-23 09:33 UTC, joschahenningsen commented
Fixed that as well, thanks :) @alexanderstephan

2022-10-23 09:58 UTC, alexanderstephan approved these changes
Works perfectly! :) 🎉

2022-10-23 09:58 UTC, merged

2022-10-24 10:50 UTC, AndreasPaul commented
A de-select all feature would be usefull