Info Pages Admin UI
joschahenningsen/TUM-Live pull request #836
Opened 2022-12-05 16:55 UTC by MatthiasReumann

### Motivation and Context
Admin Info Page UI was outdated and bugged.

### Description
Update UI with `.form-container`s. See Screenshots.

_Info: Using button classes from #792_

### Steps for Testing

Prerequisites:
- 1 Admin
- Admin Edit-Info-Pages page

1. Log in
2. Head to "Info pages"

### Screenshots
<details>
  <summary>Before:</summary>
<img width="420" alt="image" src="https://user-images.githubusercontent.com/29633518/205695288-5dab6e77-5e42-465e-92a6-ece0d1a774d7.png">
</details>

<details>
  <summary>After:</summary>
<img width="420" alt="image" src="https://user-images.githubusercontent.com/29633518/205694986-df981f34-4434-4f2a-8535-bfa2c020ccf4.png">

I changed the title to `Info Pages`. 🫠
</details>

2022-12-05 21:21 UTC, alexanderstephan requested changes
Looks really nice. 🎉  Just one small question.

2022-12-05 21:21 UTC, alexanderstephan commented on web/template/admin/admin_tabs/info-pages.gohtml
> +                <!--
Can't we remove the code that is commented out?

2022-12-06 05:29 UTC, MatthiasReumann commented on web/template/admin/admin_tabs/info-pages.gohtml
> +                <!--
Oh yeah, definitely.

2022-12-06 17:06 UTC, alexanderstephan approved these changes
🎉

2022-12-06 17:07 UTC, merged