allow getting stream from edge server with admin token
joschahenningsen/TUM-Live pull request #890
Opened 2023-01-20 07:40 UTC by joschahenningsen

### Motivation and Context

For automated scripts it's useful to be able to get streams without a jwt.

### Description

If the environment variable `ADMIN_TOKEN` is set and a provided jwt matches the token, the request is handled instead of aborted.

### Steps for Testing

Code review should be enough.

2023-01-20 23:05 UTC, alexanderstephan requested changes
Looks really good! 🍻
I only have small suggestions/remarks.

2023-01-20 23:05 UTC, alexanderstephan commented on worker/edge/README.md
> +- `ADMIN_TOKEN`: Can be used in place of the ?jwt query parameter to authenticate for streams. No default.
```suggestion
- `ADMIN_TOKEN`: Can be used in place of the `?jwt` query parameter to authenticate for streams. No default value set.
```

2023-01-20 23:05 UTC, alexanderstephan commented on worker/edge/README.md
>  - `MAIN_INSTANCE`: The url where your TUM-Live instance is available. Used for public key exchange. Defualts to `http://localhost:8081`
```suggestion
- `MAIN_INSTANCE`: The url where your TUM-Live instance is available. Used for public key exchange. Defaults to `http://localhost:8081`
```

2023-01-20 23:05 UTC, alexanderstephan commented on worker/edge/edge.go
> +		_, _ = w.Write([]byte("Forbidden"))
```suggestion
		http.Error(w, "Missing JWT", http.StatusForbidden)
```
What about using [`http.Error`](https://pkg.go.dev/net/http#Error) for all error responses?

2023-01-20 23:05 UTC, alexanderstephan commented on worker/edge/edge.go
> +var adminToken = ""
Preference, but a struct type like `edgeConfig` that groups all the proxy configurations after the first `var` block could be an alternative here. This could then be used as a receiver type for some of the methods.

2023-01-20 23:05 UTC, alexanderstephan commented on worker/edge/edge_test.go
> +	r, _ := http.NewRequest("GET", testURL+"?jwt="+str, nil)
```suggestion
	r, _ := http.NewRequest(http.MethodGet, testURL+"?jwt="+str, nil)
```
Alternatively, `http` constants could be used here. But doesn't really matter.

2023-01-22 08:50 UTC, joschahenningsen commented on worker/edge/edge.go
> +var adminToken = ""
Yes, will do when refactoring the jwt into livestreams as well.

2023-01-22 08:59 UTC, merged