Data Store
joschahenningsen/TUM-Live pull request #960
Opened 2023-03-19 01:21 UTC by mono424

### Motivation and Context
Loading data from the API and storing it was very entangled with the controllers for the UI. This makes it harder if different components need to load the same data resulting in loading sections multiple times. This could also cause inconsistencies.

### Description
A global store that stores the most update to date data, and can be subscribed to by different components, would solve the issues. This keeps the current data state consistent across all components that are using it.

### Steps for Testing
Prerequisites:
- 1 Admin
- 1 Livestream

1. Log in
2. Navigate to a Course Admin panel
3. Check if section editing works as expected
4. Go to a live stream that has sections
5. See if sections are displayed correctly
6. Add / Edit / Remove Bookmarks and chek if UI responds correctly

### Screenshots

2023-03-19 01:23 UTC, mono424 commented
@MatthiasReumann @joschahenningsen Please tell me wether you like the approach or not, its more or less just a proposal to make the data more accessible in the frontend ✌️

2023-03-27 17:06 UTC, mono424 commented
Added the possibility of a cache layer behind the providers, currently disabled, probably super unnecessary, could remove it again to reduce complexity

2023-04-03 05:02 UTC, MatthiasReumann requested changes
Awesome! Not re-loading content all the time in TS will make the page much more response 🤩

I noticed however a bit of a bug as described in the comments. Once fixed I think this PR is good to go.

2023-04-03 05:02 UTC, MatthiasReumann commented on web/ts/bookmarks.ts
> +        await DataStore.bookmarks.subscribe(this.streamId, (data) => {
If I add a new bookmark, the bookmark list on the watch page isn't updated and the callback `(data) => {}` is executed many times. Interestingly the more bookmarks exist the often the callback is called 😅

This simple test shows that
```typescript
await DataStore.bookmarks.subscribe(this.streamId, (data) => {
    console.log(data);
    this.list = data;
});
```

`data` holds only the old bookmarks without the new one.

2023-04-03 05:02 UTC, MatthiasReumann commented on web/ts/video-sections.ts
> +        await DataStore.videoSections.subscribe(this.streamId, (data) => {
This callback does also only hold the old data, however, it only is called once.

2023-04-03 05:03 UTC, MatthiasReumann commented on web/ts/bookmarks.ts
> +        await DataStore.bookmarks.subscribe(this.streamId, (data) => {
Updating and deleting bookmarks still works fine btw.

2023-04-05 17:56 UTC, mono424 commented
@MatthiasReumann As you already know I ran into trouble with AlpineJS calling `init()`-Function twice. I fixed it now with some singleton like behaviour... :S

Further, I found an issue with Course Admin Page. You cannot edit or delete Chapters, but I have the same behavior in`dev`-Branch. Should be fixed in a follow up i guess :)

2023-04-10 06:58 UTC, MatthiasReumann approved these changes
Seems to be fine now. Thanks! 💯

2023-04-10 07:00 UTC, merged